// mfe2-angular/src/app/app.ts
import { Component, signal, HostListener } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.html',
  standalone: false,
  styleUrl: './app.css'
})
export class App {
  protected readonly title = signal('Hello World from Angular MFE 2');
  protected readonly incomingMessage = signal('');

  @HostListener('window:mfe:message', ['$event'])
  onMessage(event: Event) {
    const customEvent = event as CustomEvent;
    this.incomingMessage.set(customEvent.detail);
  }

  sendMessage() {
    window.dispatchEvent(
      new CustomEvent('mfe:message', { detail: 'Hello from Angular MFE 2!' })
    );
  }
}

// mfe1-react/src/App.js
import { useState, useEffect } from 'react';
import './styles.css';

export default function App() {
  const [incomingMessage, setIncomingMessage] = useState('');

  useEffect(() => {
    const handler = (e) => setIncomingMessage(e.detail);
    window.addEventListener('mfe:message', handler);
    return () => window.removeEventListener('mfe:message', handler);
  }, []);

  const sendMessage = () => {
    window.dispatchEvent(
      new CustomEvent('mfe:message', { detail: 'Hello from React MFE 1!' })
    );
  };

  return (
    <div className="container green">
      <h1>Hello World from React MFE 1</h1>
      <button onClick={sendMessage}>Send Message to MFE 2</button>
      {incomingMessage && (
        <p className="message">Received: {incomingMessage}</p>
      )}
    </div>
  );
}
